/** ============================================================================
MIT License

Copyright (c) 2023-2025 Institute for Automotive Engineering (ika), RWTH Aachen University

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
============================================================================= */

/** Auto-generated by https://github.com/ika-rwth-aachen/etsi_its_messages -----
python3 \
  utils/codegen/codegen-py/asn1ToConversionHeader.py \
  asn1/raw/is_ts103301/IVIM-PDU-Descriptions.asn \
  asn1/raw/is_ts103301/cdd/ITS-Container.asn \
  asn1/raw/is_ts103301/iso-patched/ISO24534-3_ElectronicRegistrationIdentificationVehicleDataModule-patched.asn \
  asn1/raw/is_ts103301/iso-patched/ISO14823-missing.asn \
  asn1/raw/is_ts103301/build/asn1/TS17419_2014_CITSapplMgmtIDs.asn \
  asn1/raw/is_ts103301/iso-patched/ISO14906(2018)EfcDsrcGenericv7-patched.asn \
  asn1/raw/is_ts103301/iso-patched/ISO14906(2018)EfcDsrcApplicationv6-patched.asn \
  asn1/raw/is_ts103301/build/asn1/ISO-TS-19091-addgrp-C-2018-patched.asn \
  asn1/patched/is_ts103301/build/asn1/ISO14816_AVIAEINumberingAndDataStructures.asn \
  asn1/raw/is_ts103301/build/asn1/ISO19321IVIv2.asn \
  -t \
  ivim_ts \
  -o \
  etsi_its_conversion/etsi_its_ivim_ts_conversion/include/etsi_its_ivim_ts_conversion
----------------------------------------------------------------------------- */

/** ASN.1 Definition -----------------------------------------------------------
GddAttribute::= CHOICE{
   dtm InternationalSign-applicablePeriod, -- Date/Time/Period
   edt InternationalSign-exemptedApplicablePeriod,-- Exemption status of Date/Time/Period
   dfl InternationalSign-directionalFlowOfLane,-- Directional Flow of Lane
   ved InternationalSign-applicableVehicleDimensions,-- Vehicle Dimensions
   spe InternationalSign-speedLimits,-- Speed
   roi InternationalSign-rateOfIncline,-- Rate of Incline
   dbv InternationalSign-distanceBetweenVehicles,-- Distance Between Vehicles
   ddd InternationalSign-destinationInformation,-- Destination/Direction/Distance
   set InternationalSign-section,  -- Section
   nol InternationalSign-numberOfLane  -- Number of Lanes
   }
----------------------------------------------------------------------------- */

#pragma once

#include <etsi_its_ivim_ts_coding/ivim_ts_GddAttribute.h>
#include <etsi_its_ivim_ts_conversion/convertInternationalSignapplicablePeriod.h>
#include <etsi_its_ivim_ts_conversion/convertInternationalSignapplicableVehicleDimensions.h>
#include <etsi_its_ivim_ts_conversion/convertInternationalSigndestinationInformation.h>
#include <etsi_its_ivim_ts_conversion/convertInternationalSigndirectionalFlowOfLane.h>
#include <etsi_its_ivim_ts_conversion/convertInternationalSigndistanceBetweenVehicles.h>
#include <etsi_its_ivim_ts_conversion/convertInternationalSignexemptedApplicablePeriod.h>
#include <etsi_its_ivim_ts_conversion/convertInternationalSignnumberOfLane.h>
#include <etsi_its_ivim_ts_conversion/convertInternationalSignrateOfIncline.h>
#include <etsi_its_ivim_ts_conversion/convertInternationalSignsection.h>
#include <etsi_its_ivim_ts_conversion/convertInternationalSignspeedLimits.h>
#include <etsi_its_ivim_ts_msgs/msg/gdd_attribute.hpp>
namespace ivim_ts_msgs = etsi_its_ivim_ts_msgs::msg;


namespace etsi_its_ivim_ts_conversion {

void toRos_GddAttribute(const ivim_ts_GddAttribute_t& in, ivim_ts_msgs::GddAttribute& out) {
  switch (in.present) {
  case ivim_ts_GddAttribute_PR_dtm:
    toRos_InternationalSignapplicablePeriod(in.choice.dtm, out.dtm);
    out.choice = ivim_ts_msgs::GddAttribute::CHOICE_DTM;
    break;
  case ivim_ts_GddAttribute_PR_edt:
    toRos_InternationalSignexemptedApplicablePeriod(in.choice.edt, out.edt);
    out.choice = ivim_ts_msgs::GddAttribute::CHOICE_EDT;
    break;
  case ivim_ts_GddAttribute_PR_dfl:
    toRos_InternationalSigndirectionalFlowOfLane(in.choice.dfl, out.dfl);
    out.choice = ivim_ts_msgs::GddAttribute::CHOICE_DFL;
    break;
  case ivim_ts_GddAttribute_PR_ved:
    toRos_InternationalSignapplicableVehicleDimensions(in.choice.ved, out.ved);
    out.choice = ivim_ts_msgs::GddAttribute::CHOICE_VED;
    break;
  case ivim_ts_GddAttribute_PR_spe:
    toRos_InternationalSignspeedLimits(in.choice.spe, out.spe);
    out.choice = ivim_ts_msgs::GddAttribute::CHOICE_SPE;
    break;
  case ivim_ts_GddAttribute_PR_roi:
    toRos_InternationalSignrateOfIncline(in.choice.roi, out.roi);
    out.choice = ivim_ts_msgs::GddAttribute::CHOICE_ROI;
    break;
  case ivim_ts_GddAttribute_PR_dbv:
    toRos_InternationalSigndistanceBetweenVehicles(in.choice.dbv, out.dbv);
    out.choice = ivim_ts_msgs::GddAttribute::CHOICE_DBV;
    break;
  case ivim_ts_GddAttribute_PR_ddd:
    toRos_InternationalSigndestinationInformation(in.choice.ddd, out.ddd);
    out.choice = ivim_ts_msgs::GddAttribute::CHOICE_DDD;
    break;
  case ivim_ts_GddAttribute_PR_set:
    toRos_InternationalSignsection(in.choice.set, out.set);
    out.choice = ivim_ts_msgs::GddAttribute::CHOICE_SET;
    break;
  case ivim_ts_GddAttribute_PR_nol:
    toRos_InternationalSignnumberOfLane(in.choice.nol, out.nol);
    out.choice = ivim_ts_msgs::GddAttribute::CHOICE_NOL;
    break;
  default: break;
  }
}

void toStruct_GddAttribute(const ivim_ts_msgs::GddAttribute& in, ivim_ts_GddAttribute_t& out) {
  memset(&out, 0, sizeof(ivim_ts_GddAttribute_t));
  switch (in.choice) {
  case ivim_ts_msgs::GddAttribute::CHOICE_DTM:
    toStruct_InternationalSignapplicablePeriod(in.dtm, out.choice.dtm);
    out.present = ivim_ts_GddAttribute_PR::ivim_ts_GddAttribute_PR_dtm;
    break;
  case ivim_ts_msgs::GddAttribute::CHOICE_EDT:
    toStruct_InternationalSignexemptedApplicablePeriod(in.edt, out.choice.edt);
    out.present = ivim_ts_GddAttribute_PR::ivim_ts_GddAttribute_PR_edt;
    break;
  case ivim_ts_msgs::GddAttribute::CHOICE_DFL:
    toStruct_InternationalSigndirectionalFlowOfLane(in.dfl, out.choice.dfl);
    out.present = ivim_ts_GddAttribute_PR::ivim_ts_GddAttribute_PR_dfl;
    break;
  case ivim_ts_msgs::GddAttribute::CHOICE_VED:
    toStruct_InternationalSignapplicableVehicleDimensions(in.ved, out.choice.ved);
    out.present = ivim_ts_GddAttribute_PR::ivim_ts_GddAttribute_PR_ved;
    break;
  case ivim_ts_msgs::GddAttribute::CHOICE_SPE:
    toStruct_InternationalSignspeedLimits(in.spe, out.choice.spe);
    out.present = ivim_ts_GddAttribute_PR::ivim_ts_GddAttribute_PR_spe;
    break;
  case ivim_ts_msgs::GddAttribute::CHOICE_ROI:
    toStruct_InternationalSignrateOfIncline(in.roi, out.choice.roi);
    out.present = ivim_ts_GddAttribute_PR::ivim_ts_GddAttribute_PR_roi;
    break;
  case ivim_ts_msgs::GddAttribute::CHOICE_DBV:
    toStruct_InternationalSigndistanceBetweenVehicles(in.dbv, out.choice.dbv);
    out.present = ivim_ts_GddAttribute_PR::ivim_ts_GddAttribute_PR_dbv;
    break;
  case ivim_ts_msgs::GddAttribute::CHOICE_DDD:
    toStruct_InternationalSigndestinationInformation(in.ddd, out.choice.ddd);
    out.present = ivim_ts_GddAttribute_PR::ivim_ts_GddAttribute_PR_ddd;
    break;
  case ivim_ts_msgs::GddAttribute::CHOICE_SET:
    toStruct_InternationalSignsection(in.set, out.choice.set);
    out.present = ivim_ts_GddAttribute_PR::ivim_ts_GddAttribute_PR_set;
    break;
  case ivim_ts_msgs::GddAttribute::CHOICE_NOL:
    toStruct_InternationalSignnumberOfLane(in.nol, out.choice.nol);
    out.present = ivim_ts_GddAttribute_PR::ivim_ts_GddAttribute_PR_nol;
    break;
  default: break;
  }
}

}
