/** ============================================================================
MIT License

Copyright (c) 2023-2025 Institute for Automotive Engineering (ika), RWTH Aachen University

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
============================================================================= */

/** Auto-generated by https://github.com/ika-rwth-aachen/etsi_its_messages -----
python3 \
  utils/codegen/codegen-py/asn1ToConversionHeader.py \
  asn1/raw/is_ts103301/IVIM-PDU-Descriptions.asn \
  asn1/raw/is_ts103301/cdd/ITS-Container.asn \
  asn1/raw/is_ts103301/iso-patched/ISO24534-3_ElectronicRegistrationIdentificationVehicleDataModule-patched.asn \
  asn1/raw/is_ts103301/iso-patched/ISO14823-missing.asn \
  asn1/raw/is_ts103301/build/asn1/TS17419_2014_CITSapplMgmtIDs.asn \
  asn1/raw/is_ts103301/iso-patched/ISO14906(2018)EfcDsrcGenericv7-patched.asn \
  asn1/raw/is_ts103301/iso-patched/ISO14906(2018)EfcDsrcApplicationv6-patched.asn \
  asn1/raw/is_ts103301/build/asn1/ISO-TS-19091-addgrp-C-2018-patched.asn \
  asn1/patched/is_ts103301/build/asn1/ISO14816_AVIAEINumberingAndDataStructures.asn \
  asn1/raw/is_ts103301/build/asn1/ISO19321IVIv2.asn \
  -t \
  ivim_ts \
  -o \
  etsi_its_conversion/etsi_its_ivim_ts_conversion/include/etsi_its_ivim_ts_conversion
----------------------------------------------------------------------------- */

/** ASN.1 Definition -----------------------------------------------------------
DestinationPlace::= SEQUENCE{
   destType   					DestinationType,
   destRSCode  					GddStructure (WITH COMPONENTS {..., attributes ABSENT}) OPTIONAL,
   destBlob   					OCTET STRING OPTIONAL,
   placeNameIdentification   	INTEGER(1..999) OPTIONAL,
   placeNameText   				UTF8String OPTIONAL
   }
----------------------------------------------------------------------------- */

#pragma once

#include <etsi_its_ivim_ts_coding/ivim_ts_DestinationPlace.h>
#include <etsi_its_ivim_ts_conversion/convertDestinationType.h>
#include <etsi_its_ivim_ts_conversion/convertGddStructure.h>
#include <etsi_its_ivim_ts_coding/INTEGER.h>
#include <etsi_its_primitives_conversion/convertINTEGER.h>
#include <etsi_its_ivim_ts_coding/OCTET STRING.h>
#include <etsi_its_primitives_conversion/convertOCTET STRING.h>
#include <etsi_its_ivim_ts_coding/UTF8String.h>
#include <etsi_its_primitives_conversion/convertUTF8String.h>
#include <etsi_its_ivim_ts_msgs/msg/destination_place.hpp>
namespace ivim_ts_msgs = etsi_its_ivim_ts_msgs::msg;


namespace etsi_its_ivim_ts_conversion {

void toRos_DestinationPlace(const ivim_ts_DestinationPlace_t& in, ivim_ts_msgs::DestinationPlace& out) {
  toRos_DestinationType(in.destType, out.dest_type);
  if (in.destRSCode) {
    toRos_GddStructure(*in.destRSCode, out.dest_rs_code);
    out.dest_rs_code_is_present = true;
  }
  if (in.destBlob) {
    for (int i = 0; i < in.destBlob->list.count; ++i) {
      ivim_ts_msgs::uint8 el;
      toRos_uint8(*(in.destBlob->list.array[i]), el);
      out.dest_blob.push_back(el);
    }
    out.dest_blob_is_present = true;
  }
  if (in.placeNameIdentification) {
    etsi_its_primitives_conversion::toRos_INTEGER(*in.placeNameIdentification, out.place_name_identification);
    out.place_name_identification_is_present = true;
  }
  if (in.placeNameText) {
    etsi_its_primitives_conversion::toRos_UTF8String(*in.placeNameText, out.place_name_text);
    out.place_name_text_is_present = true;
  }
}

void toStruct_DestinationPlace(const ivim_ts_msgs::DestinationPlace& in, ivim_ts_DestinationPlace_t& out) {
  memset(&out, 0, sizeof(ivim_ts_DestinationPlace_t));
  toStruct_DestinationType(in.dest_type, out.destType);
  if (in.dest_rs_code_is_present) {
    out.destRSCode = (ivim_ts_GddStructure_t*) calloc(1, sizeof(ivim_ts_GddStructure_t));
    toStruct_GddStructure(in.dest_rs_code, *out.destRSCode);
  }
  if (in.dest_blob_is_present) {
    for (int i = 0; i < in.dest_blob.size(); ++i) {
      ivim_ts_uint8_t* el = (ivim_ts_uint8_t*) calloc(1, sizeof(ivim_ts_uint8_t));
      toStruct_uint8(in.dest_blob[i], *el);
      if (asn_sequence_add(&out.destBlob, el)) throw std::invalid_argument("Failed to add to A_SEQUENCE_OF");
    }
  }
  if (in.place_name_identification_is_present) {
    out.placeNameIdentification = (INTEGER_t*) calloc(1, sizeof(INTEGER_t));
    etsi_its_primitives_conversion::toStruct_INTEGER(in.place_name_identification, *out.placeNameIdentification);
  }
  if (in.place_name_text_is_present) {
    out.placeNameText = (UTF8String_t*) calloc(1, sizeof(UTF8String_t));
    etsi_its_primitives_conversion::toStruct_UTF8String(in.place_name_text, *out.placeNameText);
  }
}

}
